apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: authentik-cluster
  namespace: authentik
spec:
  teamId: "authentik"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    authentik:  # database owner
      - superuser
      - createdb
  databases:
    authentik: authentik
  postgresql:
    version: "16"